bench_cases:
     - name: "insert-person"
       concurrency: 10
     - name: "insert-friend"
       concurrency: 10
     - name: "get-friends-one-hop"
       concurrency: 10
     - name: "get-friends-two-hop"
       concurrency: 10
